spring:
  application:
    name: dubbo-consumer
server:
  port: 9090
request:
  service:
    version: 1.0.0
dubbo:
  scan:
    basePackages: com.xx.dubbo.consumer.controller
  application:
    id: dubbo-consumer
    name: dubbo-consumer
  protocol:
    id: dubbo
    name: dubbo
    port: 12345
    status: server
  registry:
    id: zookeeper
    address: zookeeper://47.98.246.225:2181

