spring:
  datasource:
    username: root
    password: WYZ980417
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.98.246.225:3306/study?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
